[manifest]
dump_lua = true
priority = 0
version = "1.0.0"

# Utilitools requirement ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''cs = bs.load(project.initState)'''
payload = '''
if mods.utilitools == nil then
	local buttonPressed = love.window.showMessageBox("Better Costumes", "Better Costumes requires Utilitools. Please install that mod.", { "Ok", "No" })
	if buttonPressed == 2 then error("Better Costumes: This is what you get for not installing Utilitools even though this mod needs it") end
	love.quit()
	error("Better Costumes: Failed to quit game.")
end
utilitools.files.better_costumes.startup()
'''
position = "after"
target = "main.lua"
times = 1

# Better costumes state ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''end, 17*3, nil, sprites.menu.costumes)'''
payload = '''
if mods.better_costumes.config.betterCostumes then
	self.mainMenu:addOption("Better Costumes",function()
		cs = bs.load("BetterCostumes")
		self:leave()
		cs.bg = self.bg
		cs.menuMusicManager = self.menuMusicManager
		cs:init()
	end, 17 * 8, nil, sprites.menu.costumesPlus) -- Penta: what the hell is the y value even for, it doesnt do anything visually?
end
'''
position = "after"
target = "states/Menu.lua"
times = 1

# Better costumes state ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== ===== =====
[[patches]]
[patches.pattern]
match_indent = true
pattern = '''self.randomCostume = unlockedCostumeList[math.random(#unlockedCostumeList)]'''
payload = '''
if mods.better_costumes.config.selectiveRandomness then
	local array = utilitools.table.keysToValues(mods.better_costumes.config.selectedRandomness)
	self.randomCostume = array[math.random(#array)] or "none"
else
	self.randomCostume = unlockedCostumeList[math.random(#unlockedCostumeList)]
end
'''
position = "after"
target = "obj/Player.lua"
times = 1
